name: cellpose-executor
dependencies:
  - python=3.8.5
  - pip=21.2.4
  - pip:
    - mlflow
    - addict==2.4.0                                                                                  
    - albumentations==0.5.2                                                                          
    #- cellpose==0.6.6.dev138+gd769939                                                                
    - cycler==0.10.0                                                                                 
    - cython==0.29.21                             
    - decorator==4.4.2                            
    - edt==2.1.1                                                                                     
    - fastremap==1.12.2                                                                              
    - ffmpeg-python==0.2.0                                                                           
    - future==0.18.2                                                                                 
    - imageio==2.9.0                              
    - imgaug==0.4.0                                                                                  
    - jinja2==2.11.2                                                                                 
    - joblib==1.1.0                               
    - kiwisolver==1.3.1                           
    - llvmlite==0.37.0                            
    - markupsafe==1.1.1                           
    - matplotlib==3.3.3                                                                              
    - mmcv-full==1.2.4                            
    - natsort==8.0.0                                                                                 
    - networkx==2.5                               
    - numba==0.54.1                               
    - numpy==1.20.3                               
    - opencv-python==4.4.0.46                                                                        
    - opencv-python-headless==4.4.0.46            
    - pandas==1.2.1                               
    - pyparsing==2.4.7                            
    - python-dateutil==2.8.1                      
    - pytorch-ranger==0.1.1                       
    - pytz==2021.1                                                                                   
    - pywavelets==1.1.1                           
    - pyyaml==5.3.1                               
    - roifile==2020.11.28                         
    - scikit-image==0.18.0                                                                           
    - scikit-learn==1.0.1                         
    - scipy==1.5.4                                
    - seaborn==0.11.1                             
    - shapely==1.7.1                                                                                 
    - terminaltables==3.1.0                                                                          
    - threadpoolctl==3.0.0                                                                           
    - tifffile==2020.12.8                         
    - tikzplotlib==0.9.8                          
    - torch-optimizer==0.3.0                      
    - tqdm==4.54.1                                
    - yapf==0.30.0    
    #- cellpose==0.6.5
    # brand new cellpose dependency (you should not do this due to reproducibility/stability issues)
    - git+https://github.com/MouseLand/cellpose.git#egg=cellpose[omni]
    #- opencv-python-headless==4.5.4.58
    #- torch==1.10.0
    #- scikit-image==0.18.3
    #- imageio==2.10.1
