name: cellpose-executor
dependencies:
  - python=3.8.5
  - pip=21.2.4
  - pip:
    - mlflow
    #- cellpose==0.6.5
    # brand new cellpose dependency (you should not do this due to reproducibility/stability issues)
    - git+https://github.com/MouseLand/cellpose.git#egg=cellpose[omni]
    - numpy==1.21.4
    #- opencv-python-headless==4.5.4.58
    #- torch==1.10.0
    #- scikit-image==0.18.3
    #- imageio==2.10.1
