name: cellpose-executor
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pip=21.2.4
  - cudatoolkit=10.2
  - pytorch=1.9.0
  #- _libgcc_mutex=0.1=main
  #- blas=1.0=mkl
  - pip:
    - mlflow
    - "--editable=git+https://github.com/MouseLand/cellpose.git@3b1b1e79b2b63935e2250ad05baa8128007829fd#egg=cellpose[omni]"
    #- cellpose==0.6.5
    # brand new cellpose dependency (you should not do this due to reproducibility/stability issues)
    #- opencv-python-headless==4.5.4.58
    #- torch==1.10.0
    #- scikit-image==0.18.3
    #- imageio==2.10.1
