name: cellpose-executor
dependencies:
  - python
  - pip=21.2.4=py38h06a4308_0
  - pip:
    - mlflow
    - cellpose==0.6.5
    - opencv-python-headless==4.5.4.58
    - torch==1.10.0
    - scikit-image==0.18.3
    - imageio==2.10.1
